### ISSUE TITLE
How to login with a certificate in keyvault?

### ISSUE THREAD

**Issue by charinirao** [MicrosoftDocs/azure-docs-cli#1291]
Can you provide instruction on how to login in CLI for a Service Principal with a certificate in keyvault. I created the Service principal with certificate in keyvault by lookin at instructions here - https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest 

Looks like password is getting deprecated while creating Service principal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93174b3a-3e97-8304-83fc-807be75198fe
* Version Independent ID: 1155045b-ce8c-2def-7b0e-043283f8be01
* Content: [Sign in with Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/authenticate-azure-cli.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@charinirao - Logging in directly with a certificate stored in Key Vault is not supported. In order to access Key Vault, you would need to be logged in. Instead, you must have the certificate's private key available locally. 

As stated in the instructions:

> For certificates stored in Key Vault, retrieve the certificate's private key with `az keyvault secret show`. In Key Vault, the name of the certificate's secret is the same as the certificate name. If you lose access to a certificate's private key, reset the service principal credentials.

I will edit the text here to make it clearer that the certificate's private key must be stored locally in order to connect via a certificate, whether or not the certificate was created/stored in Key Vault.

**Comment by jamesosb-msft** [comment]
So, we should use a locally stored .pfx?  I tried this, but Azure CLI just barfs up this:
The command failed with an unexpected error. Here is the traceback:

'charmap' codec can't decode byte 0x8f in position 196: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 608, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 666, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 659, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\six\six.py", line 703, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\commands\__init__.py", line 306, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\__init__.py", line 493, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli\azure\cli\command_modules\profile\custom.py", line 150, in login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\_profile.py", line 208, in find_subscriptions_on_login
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-3pnsb50r\azure-cli-core\azure\cli\core\_profile.py", line 1074, in __init__
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 196: character maps to <undefined>

It would be really helpful to actually give real examples here - actually show what I should pass for the -p argument if it's a cert stored in LocalUser\My?  Do we export it first, then pass the file?
