### ISSUE TITLE
az interactive error

### ISSUE THREAD

**Issue by kasunsjc** [MicrosoftDocs/azure-docs-cli#1343]
Hi Team,

OS - MacOS 10.14.3

When I run the az interactive it shows following errors 

az interactive
az&gt;&gt; Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/&lt;User&gt;/.azure/cliextensions/interactive/azext_interactive/azclishell/threads.py", line 21, in run
    FreshTable(self.shell).dump_command_table(self.shell)
  File "/Users/&lt;User&gt;/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 87, in dump_command_table
    main_loader.load_arguments(None)
  File "/Users/&lt;User&gt;/.azure/cliextensions/interactive/azext_interactive/azclishell/_dump_commands.py", line 33, in load_arguments
    from azure.cli.core import ArgumentsContext
ImportError: cannot import name 'ArgumentsContext' from 'azure.cli.core' (/usr/local/Cellar/azure-cli/2.0.52/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46ebbdf-461f-f220-6834-6ef2979a4e7b
* Version Independent ID: 57f78703-4efa-ea0f-7fb6-7f7dc26ab15f
* Content: [Azure CLI interactive mode](https://docs.microsoft.com/en-us/cli/azure/interactive-azure-cli?view=azure-cli-latest#feedback)
* Content Source: [docs-ref-conceptual/interactive-azure-cli.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/interactive-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@kasunsjc Please file a bug report with the engineering team: https://github.com/azure/azure-cli/issues
