### ISSUE TITLE
How to use --content-types-to-compress AZ CDN ENDPOINT CREATE

### ISSUE THREAD

**Issue by jeremyfiel** [MicrosoftDocs/azure-docs-cli#2129]
- name: --content-types-to-compress
    summary: List of content types on which compression applies. The value should be a valid MIME type.
    description: ''

Can you please provide an example of how to use this option flag in the docs? 
I'm trying to create an endpoint to optimize video on demand streaming. I can see the value "optimizationType" created when I generate the endpoint from the portal but the CLI doesn't have this option.

I tried using quotes [] and {} and nothing is working. 
"video/mpeg"
video/mpeg
{video/mpeg}
[video/mpeg]

```
az cdn endpoint create -n cdnvideojeremy --origin contenthostjeremy.blob.core.windows.net --origin-path /video -g MarketingContent --profile-name contentdeliverynetwork --content-types-to-compress {video/mpeg}
```

```
The command failed with an unexpected error. Here is the traceback:

Refuse str type as a valid iter type.
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 776, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/cdn/custom.py", line 482, in create_endpoint
    return sdk_no_wait(no_wait, client.endpoints.create, resource_group_name, profile_name, name, endpoint)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/util.py", line 514, in sdk_no_wait
    return func(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/cdn/operations/_endpoints_operations.py", line 273, in create
    **operation_config
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/cdn/operations/_endpoints_operations.py", line 212, in _create_initial
    body_content = self._serialize.body(endpoint, 'Endpoint')
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 580, in body
    return self._serialize(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 452, in _serialize
    target_obj, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 715, in serialize_data
    return self._serialize(data, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 489, in _serialize
    new_attr = self.serialize_data(orig_attr, attr_desc['type'], **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 708, in serialize_data
    data, data_type[1:-1], **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 779, in serialize_iter
    raise SerializationError("Refuse str type as a valid iter type.")
msrest.exceptions.SerializationError: Refuse str type as a valid iter type.
```

**Comment by NavtejSaini-MSFT** [comment]
@jeremyfiel The Github feedback is for improving the Github Documentation. Please provide the document link this feedback is associated with so that we can check and correctly route the issue.

If it is general product question please ask it on Microsoft Q&A platform.Please let us know if you need any further information

**Comment by jeremyfiel** [comment]
This is related to AZ-204 Developing Solutions for Microsoft Azure instructor led training course.

Lab 13.  https://github.com/jeremyfiel/AZ-204-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-204_13_lab_ak.md

```
In the Add an endpoint pop-up dialog box, perform the following actions:

In the Name text box, enter cdnvideo[yourname]**.

In the Origin type drop-down list, select Storage.

In the Origin hostname drop-down list, select the contenthost[yourname]*.blob.core.windows.net* option for the Storage account that you created earlier in this lab.

In the Origin path text box, enter /video.

Leave the Origin host header text box set to its default value.

Leave the Protocol and Origin port sections set to their default values.

**_In the Optimized for drop-down list, select Video on demand media streaming._**

Select Add.
```

I was following along in the course and using the CLI to execute the commands. The instructions for "Exercise 2: Task 5" indicate to use the portal option to "Optimize for video on demand media streaming". The CLI reference docs do not indicate how to use this option very clearly.

An example in the docs would be great. At the very least, the acceptable MIME types. I ended up using the portal to create the endpoint and then noticed a property "optimizationType" created. Is this option available to set from the CLI?

https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint?view=azure-cli-latest#az-cdn-endpoint-create

**Comment by TravisCragg-MSFT** [comment]
@jeremyfiel This is not the correct repo for CLI requests, your best bet is to [create this issue Here and choose 'Feature Request](https://github.com/Azure/azure-cli/issues/new/choose)', as this is not possible in the current iteration of the Azure CLI. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
