### ISSUE TITLE
Azure CLI ML extension version misalignment 

### ISSUE THREAD

**Issue by byronverz** [MicrosoftDocs/azure-docs-cli#2493]
The azure cli machine learning extension version in the [documentation](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest) does not correspond to the available versions when running `az extension list-available --output table` (version returned with this is 1.24.0). 

Also installing an older version of the extension is not available. When using `az extension add -n azure-cli-ml --version 1.23.0` the message returned:
```
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 660, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 716, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 694, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 331, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 808, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/extension/custom.py", line 18, in add_extension_cmd
    version=version, upgrade=upgrade)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/extension/operations.py", line 315, in add_extension
    raise CLIError(err)
knack.util.CLIError: No matching extensions for 'azure-cli-ml (1.22.0.1)'. Use --debug for more information.
```
To ensure this was not an error on the devops agent this command is being run on, I checked on my local machine what the results of `azure.cli.core.extension.operations.list_versions(‘azure-cli-ml’) ` would return and got :
```
[{'name': 'azure-cli-ml', 'version': '1.5.0', 'preview': False, 'experimental': False, 'installed': False, 'compatible': True}, {'name': 'azure-cli-ml', 'version': '1.24.0 (max compatible version)', 'preview': False
, 'experimental': False, 'installed': False, 'compatible': True}]
```
This suggests that older version installations are not supported through the extension installation arguments (or perhaps just the ml extension). 

I require version 1.23.0 of the machine learning extension for troubleshooting as I have encountered multiple errors on 1.24.0 that I did not encounter on 1.23.0 and a simple version specification when installing is not something I believe should be omitted (particularly when the [documentation](https://docs.microsoft.com/en-us/cli/azure/extension?view=azure-cli-latest#az_extension_add) shows it is possible).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4067dde0-6db0-4e37-1a8e-fe5bb9324c62
* Version Independent ID: 8ba50218-429b-2c2a-eda6-8b1cfc62615f
* Content: [Available extensions for the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-list?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/azure-cli-extensions-list.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/azure-cli-extensions-list.md)
* Product: **azure**
* Technology: **azure-cli**
* GitHub Login: @haroldrandom
* Microsoft Alias: **jianzen**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@byronverz Thanks for the feedback. We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@byronverz Thanks for the feedback. I have assigned the issue to the content author to evaluate and update the document as appropriate.

**Comment by chasewilson** [comment]
Hey @byronverz,

I'm sorry this has taken so long. It might be a moot point but is this issue persisting or should I close this issue? 

Thanks for your patience (a lot of it) and I look forward to getting this resolved

**Comment by byronverz** [comment]
Hi @chasewilson, I see the documentation and output of `az extension list-available --output table` are still different, I have managed a workaround for my issue but I don't think this type of mismatch in CLI and the docs is good. 

If keeping this ticket open will ensure this mismatch is fixed then I think it should be kept open, otherwise you can close it thanks.

**Comment by chasewilson** [comment]
Hey @byronverz, there might be a slight delay in docs vs extension list since it's auto generated and needs manual review before merge right now but we are working on shortening that difference. current ml version and doc version are the same  

Some of the extensions I can download older versions for but not all of them. I'll do some digging and see if we have standards of what extensions should support. Either way, we'll be updating clarify that part. Let me know if you have any more feedback or questions on this.
