### ISSUE TITLE
az functionapp deploy failed with an unexpected error: 'str' object has no attribute 'value'

### ISSUE THREAD

**Issue by JamieH-risual** [MicrosoftDocs/azure-docs-cli#2796]
This issue has started occurring today since my GitHub Actions runner has been updated to use Azure CLI version 2.29.0.

Step being executed:

Run azure/powershell@v1
  with:
    inlineScript: az functionapp deploy --resource-group ******* --name ********* --src-path *******/azure.parameters.json --type static --target-path parameters.json

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'str' object has no attribute 'value'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4086, in perform_onedeploy
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4252, in _perform_onedeploy_internal
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4208, in _make_onedeploy_request
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4110, in _build_onedeploy_url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 1948, in _get_scm_url
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 607, in show_webapp
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 736, in _show_app
AttributeError: 'str' object has no attribute 'value'

**Comment by AjayKumar-MSFT** [comment]
JamieH-risual,  Apologies for the in ack here! 

Thanks for leveraging Azure docs feedback channel to raise this question. Since you have closed the thread I presume the issue is resolved, if it's not the case or you need further assistance kindly just let us know (also the Azure doc for which this feedback is applicable to).

-As a side note, this channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements.
