### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by akshaybabloo** [MicrosoftDocs/azure-docs-cli#3627]
### Prerequisites

- [X] Write a descriptive title.
- [X] Search the existing issues.
- [X] I am reporting the documentation problem for the current version of Azure CLI.

### Azure CLI version being used

2.48.1

### Link to affected document

https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt

### Description of the documentation error

After installing the CLI and running the `az artifacts universal download` I get the following error:

```
Log line: No usable version of libssl was found
```

Debug output

```
cli.knack.cli: Command arguments: ['artifacts', 'universal', 'download', '--organization', 'https://dev.azure.com/FPA-PD/', '--project', '437898c5-dfae-4532-b4a1-3efd1e6fe715', '--scope', 'project', '--feed', 'ldy-ui-211-android-test', '--name', 'ldy-ui-211-android-test', '--version', '1.5.2-release', '--path', '.', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f29a3c89360>, <function OutputProducer.on_global_arguments at 0x7f29a3b83f40>, <function CLIQuery.on_global_arguments at 0x7f29a3bd11b0>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'artifacts': ['azext_devops']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: azure-devops              0.065        60       192  /home/akshay/.azure/cliextensions/azure-devops
cli.azure.cli.core: Total (1)                 0.065        60       192  
cli.azure.cli.core: Loaded 60 groups, 192 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : artifacts universal download
cli.azure.cli.core: Command table: artifacts universal download
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f29a2a56b90>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/akshay/.azure/commands/2023-05-01.11-59-34.artifacts_universal_download.122324.log'.
az_command_data_logger: command args: artifacts universal download --organization {} --project {} --scope {} --feed {} --name {} --version {} --path {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f29a2a736d0>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f29a2ab5630>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f29a2ab5750>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f29a3ba0040>, <function CLIQuery.handle_query_parameter at 0x7f29a3bd1240>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f29a2ab56c0>, <function DevCommandsLoader.post_parse_args at 0x7f29a2af2f80>]
az_command_data_logger: extension name: azure-devops
az_command_data_logger: extension version: 0.26.0
cli.azext_devops.dev.common.artifacttool_updater: Checking for a new ArtifactTool
cli.azext_devops.dev.common.artifacttool_updater: Checking for ArtifactTool updates
cli.azext_devops.dev.common.services: PAT is present which can be used against this instance
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azext_devops.dev.common.services: az login is not present
cli.azext_devops.dev.common.services: There are no active accounts.
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 537, in get_current_account_user
    active_account = self.get_subscription()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 546, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 61, in _get_credentials
    token_from_az_login = get_token_from_az_logins(organization, pat_token_present)
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 118, in get_token_from_az_logins
    dummy_user = profile.get_current_account_user()     # noqa: F841
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 539, in get_current_account_user
    raise CLIError('There are no active accounts.')
knack.util.CLIError: There are no active accounts.
cli.azext_devops.dev.common.services: received PAT from environment variable
cli.azext_devops.dev.common.services: Creating connection with personal access token.
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
cli.azext_devops.dev.common.telemetry: Azure devops telemetry enabled.
cli.azext_devops.dev.common.telemetry: Logging telemetry to azure devops server.
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache: Loading cache file: /home/akshay/.azure-devops/python-sdk/cache/options.json
azext_devops.devops_sdk._file_cache: attempting to read file /home/akshay/.azure-devops/python-sdk/cache/options.json as utf-8-sig
azext_devops.devops_sdk.client: File cache hit for options on: https://dev.azure.com/fpa-pd
azext_devops.devops_sdk.client: Route template: _apis/{area}/{resource}
azext_devops.devops_sdk.client: Api version '5.0-preview.1'
azext_devops.devops_sdk.client: POST https://dev.azure.com/fpa-pd/_apis/CustomerIntelligence/Events
azext_devops.devops_sdk.client: Request content: [{'area': 'AzureDevopsCli', 'feature': 'artifacts', 'properties': {'Command': 'universal download', 'Args': 'feed name version path scope organization project', 'ShellType': '/bin/bash', 'IsInteractive': 'True', 'OutputType': 'json', 'OrgPresentInCommand': True, 'ProjectPresentInCommand': True, 'RepoPresentInCommand': False}}]
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): dev.azure.com:443
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache: Loading cache file: /home/akshay/.azure-devops/python-sdk/cache/resources.json
azext_devops.devops_sdk._file_cache: attempting to read file /home/akshay/.azure-devops/python-sdk/cache/resources.json as utf-8-sig
azext_devops.devops_sdk.connection: File cache hit for resources on: https://dev.azure.com/fpa-pd
msrest.universal_http.requests: Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
cli.azext_devops.dev.common.artifacttool_updater: Looking up current version of ArtifactTool...
azext_devops.devops_sdk.client: File cache hit for options on: https://vsblob.dev.azure.com/fpa-pd
azext_devops.devops_sdk.client: Route template: _apis/{area}/{toolName}/{resource}
azext_devops.devops_sdk.client: Api version '5.0-preview'
azext_devops.devops_sdk.client: GET https://vsblob.dev.azure.com/FPA-PD/_apis/clienttools/ArtifactTool/release?osName=Linux&arch=x86_64&distroName=ubuntu&distroVersion=22.04
azext_devops.devops_sdk.client: Request content: None
msrest.universal_http: Configuring redirects: allow=True, max=30
msrest.universal_http: Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http: Configuring proxies: ''
msrest.universal_http: Evaluate proxies against ENV settings: True
urllib3.connectionpool: Starting new HTTPS connection (1): vsblob.dev.azure.com:443
urllib3.connectionpool: https://vsblob.dev.azure.com:443 "GET /FPA-PD/_apis/clienttools/ArtifactTool/release?osName=Linux&arch=x86_64&distroName=ubuntu&distroVersion=22.04 HTTP/1.1" 200 442
azext_devops.devops_sdk.client: Response content: b'{"name":"ArtifactTool","rid":"linux-x64","version":"0.2.267","uri":"https://044vsblobprodeau135.vsblob.vsassets.io/artifacttool/artifacttool-linux-x64-Release_0.2.267.zip?sv=2019-07-07&sr=b&sig=xDnQi2OsHeCxb0Hxz0aikXJE0UBQX2SbU6yw1FsFIAA%3D&spr=https&se=2023-05-01T00%3A59%3A35Z&sp=r&P1=1682902475&P2=11&P3=2&P4=%2fbuZYm9U3sNBaAjCsRnUjT53j80g3LamrXoD1sNxlGU%3d"}'
cli.azext_devops.dev.common.artifacttool_updater: Checking if we already have ArtifactTool release 'ArtifactTool_linux-x64_0.2.267'
cli.azext_devops.dev.common.artifacttool_updater: Not updating ArtifactTool because the current release already exists at '/home/akshay/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.267'
cli.azext_devops.dev.common.services: PAT is present which can be used against this instance
cli.azure.cli.core: Current cloud config:
AzureCloud
cli.azext_devops.dev.common.services: az login is not present
cli.azext_devops.dev.common.services: There are no active accounts.
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 537, in get_current_account_user
    active_account = self.get_subscription()
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 546, in get_subscription
    raise CLIError(_AZ_LOGIN_MESSAGE)
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 61, in _get_credentials
    token_from_az_login = get_token_from_az_logins(organization, pat_token_present)
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 118, in get_token_from_az_logins
    dummy_user = profile.get_current_account_user()     # noqa: F841
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/_profile.py", line 539, in get_current_account_user
    raise CLIError('There are no active accounts.')
knack.util.CLIError: There are no active accounts.
cli.azext_devops.dev.common.services: received PAT from environment variable
cli.azext_devops.dev.common.services: Creating connection with personal access token.
cli.azext_devops.dev.common.external_tool: Running external command: /home/akshay/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.267/artifacttool universal download --service https://dev.azure.com/FPA-PD/ --patvar AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR --feed ldy-ui-211-android-test --package-name ldy-ui-211-android-test --package-version 1.5.2-release --path . --project 437898c5-dfae-4532-b4a1-3efd1e6fe715
urllib3.connectionpool: https://dev.azure.com:443 "POST /fpa-pd/_apis/CustomerIntelligence/Events HTTP/1.1" 401 0
msrest.exceptions: The requested resource requires user authentication: https://dev.azure.com/fpa-pd/_apis/CustomerIntelligence/Events
cli.azext_devops.dev.common.telemetry: The requested resource requires user authentication: https://dev.azure.com/fpa-pd/_apis/CustomerIntelligence/Events
Traceback (most recent call last):
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/telemetry.py", line 86, in _send_tracking_ci_event
    ci_client.publish_events([vsts_tracking_data])
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/v5_0/customer_intelligence/customer_intelligence_client.py", line 20, in publish_events
    self._send(http_method='POST',
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 90, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 54, in _send_request
    self._handle_error(request, response)
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/devops_sdk/client.py", line 253, in _handle_error
    raise AzureDevOpsAuthenticationError(full_message_format.format(error_message=error_message,
azext_devops.devops_sdk.exceptions.AzureDevOpsAuthenticationError: The requested resource requires user authentication: https://dev.azure.com/fpa-pd/_apis/CustomerIntelligence/Events
cli.azext_devops.dev.common.artifacttool: Failed to parse structured output from Universal Packages tooling (ArtifactTool)
cli.azext_devops.dev.common.artifacttool: Exception: Expecting value: line 1 column 1 (char 0)
cli.azext_devops.dev.common.artifacttool: Log line: No usable version of libssl was found
cli.azext_devops.dev.common.exception_handler: handling generic error
cli.azure.cli.core.azclierror: Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.10/site-packages/six.py", line 719, in reraise
    raise value
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/artifacts/universal.py", line 98, in download_package
    return artifact_tool.download_universal(organization, project, feed, name, version, path, file_filter)
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool.py", line 42, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/artifacttool.py", line 67, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/external_tool.py", line 79, in run
    return self.wait()
  File "/home/akshay/.azure/cliextensions/azure-devops/azext_devops/dev/common/external_tool.py", line 51, in wait
    raise CLIError(
knack.util.CLIError: Process ['/home/akshay/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.267/artifacttool', 'universal', 'download', '--service', 'https://dev.azure.com/FPA-PD/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', 'ldy-ui-211-android-test', '--package-name', 'ldy-ui-211-android-test', '--package-version', '1.5.2-release', '--path', '.', '--project', '437898c5-dfae-4532-b4a1-3efd1e6fe715'] with PID 122330 exited with return code -6

cli.azure.cli.core.azclierror: Process ['/home/akshay/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.267/artifacttool', 'universal', 'download', '--service', 'https://dev.azure.com/FPA-PD/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', 'ldy-ui-211-android-test', '--package-name', 'ldy-ui-211-android-test', '--package-version', '1.5.2-release', '--path', '.', '--project', '437898c5-dfae-4532-b4a1-3efd1e6fe715'] with PID 122330 exited with return code -6
az_command_data_logger: Process ['/home/akshay/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.267/artifacttool', 'universal', 'download', '--service', 'https://dev.azure.com/FPA-PD/', '--patvar', 'AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR', '--feed', 'ldy-ui-211-android-test', '--package-name', 'ldy-ui-211-android-test', '--package-version', '1.5.2-release', '--path', '.', '--project', '437898c5-dfae-4532-b4a1-3efd1e6fe715'] with PID 122330 exited with return code -6
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f29a2a56dd0>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 1.670 seconds (init: 0.212, invoke: 1.458)
telemetry.main: Begin splitting cli events and extra events, total events: 1
telemetry.client: Accumulated 0 events. Flush the clients.
telemetry.main: Finish splitting cli events and extra events, cli events: 1
telemetry.save: Save telemetry record of length 3946 in cache
telemetry.check: Negative: The /home/akshay/.azure/telemetry.txt was modified at 2023-05-01 11:49:46.563550, which in less than 600.000000 s
```

### Suggested fix

From Ubuntu 22.04 `libssl` is not supported, instead its replaced with `libssl3`. I think the CLI needs to use the new one

**Comment by ManoharLakkoju-MSFT** [comment]
Unable to add meta data above .

Document Details
⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
Content: [Install the Azure CLI on Linux](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=zypper#update)
Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/install-azure-cli-linux.md)
Service: azure-cli
GitHub Login: @ChaseCrum
Microsoft Alias: chasecrum

**Comment by ChaseCrum** [comment]
@akshaybabloo
Thank you for helping to make the Azure CLI better. As this is an application issue, your comments have been moved to the Azure/azurecli GitHub source code repository. Please continue to track this issue under issue #[26338](https://github.com/Azure/azure-cli/issues/26338).
